baseURL = "http://aaronkulbe.com/"
languageCode = "en-us"
title = "aaron kulbe"
theme = 'PaperMod'

[author]
    name = "aaron kulbe"
    email = "aaron@kulbe.name"
    github = "akulbe"
    twitter = "akulbe"
    devto = "akulbe"

[module]
[[module.imports]]
  path = 'github.com/adityatelange/hugo-PaperMod'
